travis:
  secure:
    BINSTAR_TOKEN: Ek0a4SWy24Ue7fQRQxAIkk59c9PmCEhFmHVDMaqLjMVf++iRAAQCY8HFmTHsj8YCpkt+63iFWbkHYIokTYfKBNHaw7HCAbOc7OxcGNjOhpsb6Xd0I9DHGxLJblem34KAufoc8MS83Am3Hxs5bVmTzBd97bFUOq39/1VBRQc6lqORAfocpWmDYEsiuwjulqQEIO7uXYoSnMpxkbAwEkhQBbkl3IHdrQ4dLMVc56idpOqdbIvUV1N4P+25i1yGbZvmsNsq1SOUUjrptNsaeFfMUuFUpRiUj3YsAs0KrJykOQnTyCPhZ3b2QRhVG5l0JGofnIYUAnLe9cV/rJqPAwJD/+QIVV0xwUb6G6q+B08kQeyhTpbFaRCmnIUSITozrDJZu4aVPEBbHXb6BuN4MLqj11WvEbyYm3zXVMKr9Dy25oTmCty8qDkjLiaFXUCQPhUScUr4p40Tdjh8/iZJ/ySbphN84Md3Yqckc8IrDzSuuPH1t7GlX6AStfSdoTV/z1c/2GT/o0Wg3EX5KtQzGGLeGnG8pCNiI6SsYVcZhiSzWLa7bTFK85mo28S7maRzGyBFtEMRNQ6283emebgXxGccVqBcBCI3ZWbmBLh4BYke5hcaB7mI93b4Nj6mLIsx9RQm8mJ+kENU2Dw+Q+NHuuPxvDmXmIZiqQFwJX57Tdz7mho=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
