travis:
  secure:
    BINSTAR_TOKEN: hLcztsZaUbF4V5c8MtNi2R1teguATxYIzKSVHr462zm5uJ4SDqk0UhBSmpqFFt6vJHhFe0a6zB/F13lfIuZecMyIEqr9PUYUOfDR4GN+NVKJps3rTUhbMQGkBhDuW7E9IP5QsTR3NCa5nitFMqMZ5gL3wOdcND+o3NUYaD4lH9dN/sDCHmzj/cKvZjWKtFspSrHtI6NBmzbU1IAfUuxIUIy/d/sYEdOSDSqqU6LXSHwjMiVEc+3ZzdwObhDA3JiFbX87ZGKp7AlEOcvZKZqQuEQlPJs6mBsgeFIOHiSf46lkA+WDqttS+5+6KY+SKHPD+rIXRRd5e9fo0YYK86Sfm2plx6zGdaf41TcQ2E3Yr79FGuQEMdun8nud3mFHGrvZv2i3QlLS5DfLIErWEKPrihds8nHGz4i/Ok+0MFsaqhosj//Lw4tjOPz3qPKhdLHXiQXBup9rzLXvfhkFKuWNx5GFEQmTLCaIhBvjxIzJXQLBzVi8ik9dOwVWPzuVbnpZn9C6+s6TDk33IWLQKvM0eMnC7JKzZipljRucvEPqGIiTm8457MGSo+WFjYhESD4jNgyShUJQiLnlo8+EJM46PRlOkbRhX/5w3x5C9kIhkRVhND7oeJtgUsDjHgapGszRNzAksr9aAaHQvRTLtotgpBAmPn/beDhmg/595Xt8Y5M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
